words = [
    "actionlint",
    "akinsho",
    "annote",
    "ansible",
    "ansiblelint",
    "autopush",
    "autosnippets",
    "avante",
    "bdel",
    "bdele",
    "bdelete",
    "blanklines",
    "bof",
    "bufdelete",
    "bwip",
    "bwipe",
    "bydlw",
    "chezmoi",
    "clearjumps",
    "cnext",
    "conceallevel",
    "copen",
    "cprev",
    "crc",
    "cursorline",
    "cza",
    "czp",
    "czw",
    "czz",
    "diffthis",
    "editmsg",
    "folke",
    "gitlint",
    "gitrebase",
    "gitsigns",
    "globalstatus",
    "gra",
    "gri",
    "grn",
    "grr",
    "gzz",
    "hadolint",
    "jsregexp",
    "junegunn",
    "keeppatterns",
    "kylechui",
    "lazydev",
    "lazypath",
    "lnext",
    "lprev",
    "lualine",
    "luasnip",
    "mapleader",
    "matchit",
    "matchparen",
    "mdsf",
    "mdslw",
    "misconfig",
    "mypy",
    "mzr",
    "mzvzcz",
    "mzx",
    "netrw",
    "nls",
    "noname",
    "nonblank",
    "nvimtools",
    "omni",
    "pcall",
    "polarmutex",
    "redir",
    "relativenumber",
    "rtp",
    "runtimepath",
    "saghen",
    "scrolloff",
    "setqflist",
    "sidescrolloff",
    "signcolumn",
    "statusline",
    "tabline",
    "tabnext",
    "tabpage",
    "tabprev",
    "tiktoken",
    "tohtml",
    "tpope",
    "trigg",
    "unpulled",
    "unpushed",
    "virt",
    "williamboman",
    "winbar",
    "wincmd",
    "xnext",
    "xprev",
    "zbirenbaum",
]
