words = [
    "buflisted",
    "bufnr",
    "bufs",
    "buftype",
    "cssls",
    "esc",
    "foldexpr",
    "ghostty",
    "gitcommit",
    "htmx",
    "jsonls",
    "keymaps",
    "linehl",
    "linewise",
    "linters",
    "loclist",
    "mins",
    "nop",
    "numhl",
    "nvim",
    "pyright",
    "qflist",
    "qfloclist",
    "stylua",
    "taplo",
    "textobjects",
    "theprimeagen",
    "yamlls",
    "yanky",
]
