return {
	"stevearc/aerial.nvim",
	dependencies = "nvim-telescope/telescope.nvim",
	cmd = "Telescope aerial",
	keys = {
		{ "<leader>A", "<cmd>AerialToggle!<cr>", desc = "Aerial" },
	},
	config = function()
		require("aerial").setup({
			backends = { "treesitter", "lsp", "markdown", "man" },
			layout = {
				default_direction = "prefer_right",
				min_width = 20,
			},
			keymaps = {
				["?"] = "actions.show_help",
				["g?"] = "actions.show_help",
				["<CR>"] = "actions.jump",
				["<2-LeftMouse>"] = "actions.jump",
				["<C-v>"] = "actions.jump_vsplit",
				["<C-s>"] = "actions.jump_split",
				["p"] = "actions.scroll",
				["<C-k>"] = "actions.down_and_scroll",
				["<C-h>"] = "actions.up_and_scroll",
				["k"] = "actions.prev",
				["h"] = "actions.next",
				["{"] = "actions.prev",
				["}"] = "actions.next",
				["[["] = "actions.prev_up",
				["]]"] = "actions.next_up",
				["q"] = "actions.close",
				["o"] = "actions.tree_toggle",
				["za"] = "actions.tree_toggle",
				["O"] = "actions.tree_toggle_recursive",
				["zA"] = "actions.tree_toggle_recursive",
				["l"] = "actions.tree_open",
				["zo"] = "actions.tree_open",
				["L"] = "actions.tree_open_recursive",
				["zO"] = "actions.tree_open_recursive",
				["j"] = "actions.tree_close",
				["zc"] = "actions.tree_close",
				["J"] = "actions.tree_close_recursive",
				["zC"] = "actions.tree_close_recursive",
				["zr"] = "actions.tree_increase_fold_level",
				["zR"] = "actions.tree_open_all",
				["zm"] = "actions.tree_decrease_fold_level",
				["zM"] = "actions.tree_close_all",
				["zx"] = "actions.tree_sync_folds",
				["zX"] = "actions.tree_sync_folds",
			},
		})
	end,
}
