local next, prev = require("utils").repeatable(function()
    require("vim.treesitter._headings").jump({ count = 1, level = 1 })
    vim.cmd("normal! zt")
end, function()
    require("vim.treesitter._headings").jump({ count = -1, level = 1 })
    vim.cmd("normal! zt")
end)
vim.keymap.set("n", "[[", prev, { buf = 0, silent = false, desc = "Goto previous section" })
vim.keymap.set("n", "]]", next, { buf = 0, silent = false, desc = "Goto next section" })
