-- stylua: ignore start
local u = require("utils")
local set = u.keymap.set
local del = vim.keymap.del

--- General
set("n", "<C-c>", vim.cmd.noh, { desc = "Clear highlights" })
set("n", "<Esc>", vim.cmd.noh, { desc = "Clear highlights" })
set("c", "<Esc>", "<C-c>",     { desc = "cancel"})
set("i", "<Esc>", u.escape,    { desc = "Preserve cursor pos", expr = true})
set("i", "<C-c>", u.escape,    { desc = "Preserve cursor pos", expr = true})

--- Cursor Navigation
set("n", "k",     "v:count == 0 ? 'gj' : 'j'", { desc = "Down",  silent = true, expr = true })
set("n", "h",     "v:count == 0 ? 'gk' : 'k'", { desc = "Up",    silent = true, expr = true })
set("n", "j",     "h",                         { desc = "Left",  silent = true })
set("n", "l",     "l",                         { desc = "Right", silent = true })
set("x", "k",     "j",                         { desc = "Down",  silent = true })
set("x", "h",     "k",                         { desc = "Up",    silent = true })
set("x", "j",     "h",                         { desc = "Left",  silent = true })
set("x", "l",     "l",                         { desc = "Right", silent = true })
set("n", "gk",    "j",                         { desc = "Down",  silent = true })
set("n", "gh",    "k",                         { desc = "Up",    silent = true })
set("c", "<A-f>", u.cmode_next_word,           { desc = "Next word", expr = true })
set("c", "<A-b>", u.cmode_prev_word,           { desc = "Prev word", expr = true })
set("c", "<C-a>", "<Home>",                    { desc = "BoL" })
set("c", "<C-e>", "<End>",                     { desc = "EoL" })
set("n", "ge",    "gi",                        { desc = "Goto last edited" })
set("n", "gg",    "gg",                        { desc = "Goto BoF" })
set("n", "G",     "Gzb",                       { desc = "Goto EoF" })
set("n", "}",     "}zz",                       { desc = "Next Paragraph" })
set("n", "{",     "{zz",                       { desc = "Prev Paragraph" })
set("n", "'",     "g`",                        { desc = "Jump to mark" })
set("n", "zt",         "zt",      { desc = "Redraw window (top)" })
set("n", "zb",         "zb",      { desc = "Redraw window (bottom)" })
set("n", "<C-d>",      "<C-d>zz", { desc = "Scroll down" })
set("n", "<C-u>",      "<C-u>zz", { desc = "Scroll up" })
set("n", "<PageDown>", "<C-d>zz", { desc = "Scroll down" })
set("n", "<PageUp>",   "<C-u>zz", { desc = "Scroll up" })
set("n", "<C-e>",      "4<C-e>",  { desc = "Scroll down" })
set("n", "<C-y>",      "4<C-y>",  { desc = "Scroll up" })
set("n", "zj",         "8zh",     { desc = "Scroll left" })
set("n", "zl",         "8zl",     { desc = "Scroll right" })
set("n", "zJ",         "16zh",    { desc = "Scroll left" })
set("n", "zL",         "16zl",    { desc = "Scroll right" })
set("n", "zh",         "<Nop>",   { desc = "NOP"})
set("n", "zH",         "<Nop>",   { desc = "NOP"})

-- Buffer/Tab/Pane Navigation & Management
set("n", "<C-q>",     "<cmd>q<cr>",                  { desc = "Close buffer"  })
set("n", "<C-s>",     "<cmd>silent w<cr>",           { desc = "Write buffer" })
set("n", "<Home>",    "<cmd>tabprev<cr>",            { desc = "Previous tab" })
set("n", "<End>",     "<cmd>tabnext<cr>",            { desc = "Next tab" })
set("n", "<c-w>K",    "<c-w>J",                      { desc = "Move pane to down" })
set("n", "<c-w>H",    "<c-w>K",                      { desc = "Move pane to up" })
set("n", "<c-w>J",    "<c-w>H",                      { desc = "Move pane to left" })
set("n", "<c-w>L",    "<c-w>L",                      { desc = "Move pane to right" })
set("n", "<C-Up>",    "<cmd>resize +2<cr>",          { desc = "Increase window height" })
set("n", "<C-Down>",  "<cmd>resize -2<cr>",          { desc = "Decrease window height" })
set("n", "<C-Left>",  "<cmd>vertical resize -2<cr>", { desc = "Decrease window width" })
set("n", "<C-Right>", "<cmd>vertical resize +2<cr>", { desc = "Increase window width" })
set("n", "<C-t>", u.alt_buf, { desc = "Open alternate buffer" })

-- Fold
local function fold(level) return function() vim.wo.foldlevel = level end end
set("n", "z0", fold(0), { desc = "Fold level: 0" })
set("n", "z1", fold(1), { desc = "Fold level: 1" })
set("n", "z2", fold(2), { desc = "Fold level: 2" })
set("n", "z3", fold(3), { desc = "Fold level: 3" })
set("n", "z4", fold(4), { desc = "Fold level: 4" })
set("n", "z5", fold(5), { desc = "Fold level: 5" })
set("n", "zv", "zMzx",  { desc = "Open enough fold" }) -- zMzvzczO
set("n", "zx", "zMzx",  { desc = "Open enough fold" })
set("n", "zi", function() vim.lsp.foldclose("imports") end, { desc = "Fold imports" })
set("n", "z/", function() vim.lsp.foldclose("comment") end, { desc = "Fold comments" })

-- Editing
set("i",  "<C-s>",      "<C-d>",                  { desc = "Indent -1 level" })
set("i",  "<C-t>",      "<C-t>",                  { desc = "Indent +1 level" })
set("n",  "<<",         "<h",                     { desc = "Indent -1 level" })
set("n",  ">>",         ">l",                     { desc = "Indent +1 level" })
set("v",  "<",          "<gv",                    { desc = "Indent -1 level" })
set("v",  ">",          ">gv",                    { desc = "Indent +1 level" })
set("ic", "<A-BS>",     "<C-w>",                  { desc = "Delete word" }) -- delete word
set("ic", "<A-Del>",    "<C-o>dw",                { desc = "Delete word forward" })
set("s",  "<BS>",       "<BS>i",                  { desc = "Delete selection" })
set("i",  "<C-d>",      "<Del>",                  { desc = "Delete forward" })
set("i",  "<C-k>",      "<C-o>D",                 { desc = "Delete to EOL" })
set("n",  "J",          "mzJ`z",                  { desc = "Join lines" }) -- join lines while preserving cursor pos
set("x",  "p",          '"_dP',                   { desc = "Preserve clipboard" }) -- keep copied text in register without overriding when pasting/replacing -- "greatest remap ever" by thePrimeagen
set("n",  "<A-down>",   ":m .+1<CR>==",           { desc = "Move line below" })
set("i",  "<A-down>",   "<Esc>:m .+1<CR>==gi",    { desc = "Move line below" })
set("v",  "<A-down>",   ":m '>+1<CR>gv=gv",       { desc = "Move line below" })
set("n",  "<A-k>",      ":m .+1<CR>==",           { desc = "Move line below" })
set("i",  "<A-k>",      "<Esc>:m .+1<CR>==gi",    { desc = "Move line below" })
set("v",  "<A-k>",      ":m '>+1<CR>gv=gv",       { desc = "Move line below" })
set("n",  "<A-up>",     ":m .-2<CR>==",           { desc = "Move line up" })
set("i",  "<A-up>",     "<Esc>:m .-2<CR>==gi",    { desc = "Move line up" })
set("v",  "<A-up>",     ":m '<-2<CR>gv=gv",       { desc = "Move line up" })
set("n",  "<A-h>",      ":m .-2<CR>==",           { desc = "Move line up" })
set("i",  "<A-h>",      "<Esc>:m .-2<CR>==gi",    { desc = "Move line up" })
set("v",  "<A-h>",      ":m '<-2<CR>gv=gv",       { desc = "Move line up" })
set("n",  "<leader>rw", u.trim_buf,               { desc = "Remove unnecessary whitespace" })
set("n",  "dA",         "<cmd>%delete<cr>",       { desc = "Delete all" })
set("n",  "yA",         "<cmd>%yank<cr>",         { desc = "Yank all" })
set("n",  "<leader>y",  u.yank_location,          { desc = "Yank current location" })
set("n",  "<leader>Y",  u.yank_location_and_line, { desc = "Yank current location and content" })

-- Display/Toggle: <leader>d
set("n", "<leader>dm", "<cmd>message<cr>",       { desc = "Messages" })
set("n", "<leader>dM", "<cmd>Redir message<cr>", { desc = "Redir Messages" })
set("n", "<leader>dn", u.toggle_gutter,          { desc = "Display Numbers" })
set("n", "<leader>dl", u.toggle_conceal,         { desc = "Conceal Toggle" })
set("n", "<leader>dw", u.toggle_wrap,            { desc = "Wrap Line Toggle" })
-- set("n", "<leader>ds", u.toggle_spell,           { desc = "Spelling Toggle" })

-- quickfix & loclist
set("n", "]x", u.xnext, { desc = "Goto next qfloclist item" })
set("n", "[x", u.xprev, { desc = "Goto previous qfloclist item" })
set("n", "]q", u.cnext, { desc = "Goto next qflist" })
set("n", "[q", u.cprev, { desc = "Goto previous qflist" })
set("n", "]l", u.lnext, { desc = "Goto next loclist" })
set("n", "[l", u.lprev, { desc = "Goto previous loclist" })
set("n", "<leader>xx", u.toggle_workspace_diagnostic, { desc = "Workspace diagnostics" })
set("n", "<leader>xd", u.toggle_buf_diagnostic,       { desc = "Buffer diagnostics" })
set("n", "<leader>xh", u.toggle_info_diagnostic,      { desc = "Hint & Info diagnostics" })
set("n", "<leader>xc", u.cclose,                      { desc = "Close qfloclist" })
set("n", "<leader>xq", vim.cmd.copen,                 { desc = "Open qflist" })
set("n", "<leader>xl", vim.cmd.lopen,                 { desc = "Open loclist" })

-- etc
set("n", "<leader>rz", [[<cmd>s!\v(https://)?(www\.)?github.com/([^/]+/[^/]+).*!\3<cr><cmd>noh<cr>]],                { desc = "Clean GitHub url for Lazy" })
set("n", "<leader>rg", [[<cmd>s!\v(https://)?(www\.)?(github\.com/[^/]+/[^/]+).*!\1\2\3!<cr><cmd>noh<cr>]],          { desc = "Clean GitHub url" })
set("n", "<leader>rl", [[<cmd>s!\v(https://)?(www\.)?(leetcode\.com/problems/)([^/]+).*!\1\2\3\4!<cr><cmd>noh<cr>]], { desc = "Clean LeetCode url" })

-- Temp test
set("n", "<C-CR>",    function() vim.notify("control enter pressed",     vim.log.levels.ERROR) end)
set("n", "<ESC><CR>", function() vim.notify("shift enter pressed",       vim.log.levels.ERROR) end)
set("n", "<Esc>'",    function() vim.notify("control ' (esc') pressed",  vim.log.levels.ERROR) end)
set("n", "<Esc>;",    function() vim.notify("control ; (esc;) pressed",  vim.log.levels.ERROR) end)
set("n", "<C-_>",     function() vim.notify("control _ (ctrl /)pressed", vim.log.levels.ERROR) end)

-- disable defaults
del("n", "grn")
del("n", "gra")
del("n", "grr")
del("n", "gri")
del("n", "grt")
del("n", "gO")
del("n", "[t")
del("n", "]t")
del("n", "[T")
del("n", "]T")
del("n", "[b")
del("n", "]b")
del("n", "[B")
del("n", "]B")
del("n", "[A")
del("n", "]A")
del("n", "[<C-q>")
del("n", "]<C-q>")
del("n", "[<C-l>")
del("n", "]<C-l>")
del("n", "[<C-t>")
del("n", "]<C-t>")
